//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Files", Namespace="http://schemas.datacontract.org/2004/07/ModelFirst")]
    public partial class Files : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private ModelFirst.Persoane[] PersoanesField;
        
        private ModelFirst.Useri[] UserisField;
        
        private string caleField;
        
        private System.DateTime data_creareField;
        
        private int delField;
        
        private string descriereField;
        
        private string evenimentField;
        
        private string locatieField;
        
        private string nume_fisierField;
        
        private string peisajField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ModelFirst.Persoane[] Persoanes
        {
            get
            {
                return this.PersoanesField;
            }
            set
            {
                this.PersoanesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ModelFirst.Useri[] Useris
        {
            get
            {
                return this.UserisField;
            }
            set
            {
                this.UserisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cale
        {
            get
            {
                return this.caleField;
            }
            set
            {
                this.caleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime data_creare
        {
            get
            {
                return this.data_creareField;
            }
            set
            {
                this.data_creareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int del
        {
            get
            {
                return this.delField;
            }
            set
            {
                this.delField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descriere
        {
            get
            {
                return this.descriereField;
            }
            set
            {
                this.descriereField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string eveniment
        {
            get
            {
                return this.evenimentField;
            }
            set
            {
                this.evenimentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string locatie
        {
            get
            {
                return this.locatieField;
            }
            set
            {
                this.locatieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nume_fisier
        {
            get
            {
                return this.nume_fisierField;
            }
            set
            {
                this.nume_fisierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string peisaj
        {
            get
            {
                return this.peisajField;
            }
            set
            {
                this.peisajField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persoane", Namespace="http://schemas.datacontract.org/2004/07/ModelFirst")]
    public partial class Persoane : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ModelFirst.Files[] FilesField;
        
        private int IdField;
        
        private int delField;
        
        private string nume_persoanaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ModelFirst.Files[] Files
        {
            get
            {
                return this.FilesField;
            }
            set
            {
                this.FilesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int del
        {
            get
            {
                return this.delField;
            }
            set
            {
                this.delField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nume_persoana
        {
            get
            {
                return this.nume_persoanaField;
            }
            set
            {
                this.nume_persoanaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Useri", Namespace="http://schemas.datacontract.org/2004/07/ModelFirst")]
    public partial class Useri : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ModelFirst.Files[] FilesField;
        
        private int IdField;
        
        private int delField;
        
        private string mailField;
        
        private string nume_completField;
        
        private string parolaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ModelFirst.Files[] Files
        {
            get
            {
                return this.FilesField;
            }
            set
            {
                this.FilesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int del
        {
            get
            {
                return this.delField;
            }
            set
            {
                this.delField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mail
        {
            get
            {
                return this.mailField;
            }
            set
            {
                this.mailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nume_complet
        {
            get
            {
                return this.nume_completField;
            }
            set
            {
                this.nume_completField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parola
        {
            get
            {
                return this.parolaField;
            }
            set
            {
                this.parolaField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="InterfaceWCF")]
public interface InterfaceWCF
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/AddFile", ReplyAction="http://tempuri.org/InterfaceWCF/AddFileResponse")]
    void AddFile(string Nume_fisier, string Cale, System.DateTime Data_creare, string Locatie, string Eveniment, string Peisaj, string Descriere);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/AddFile", ReplyAction="http://tempuri.org/InterfaceWCF/AddFileResponse")]
    System.Threading.Tasks.Task AddFileAsync(string Nume_fisier, string Cale, System.DateTime Data_creare, string Locatie, string Eveniment, string Peisaj, string Descriere);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/AddPersoane", ReplyAction="http://tempuri.org/InterfaceWCF/AddPersoaneResponse")]
    void AddPersoane(string Nume_persoana);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/AddPersoane", ReplyAction="http://tempuri.org/InterfaceWCF/AddPersoaneResponse")]
    System.Threading.Tasks.Task AddPersoaneAsync(string Nume_persoana);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/AddUser", ReplyAction="http://tempuri.org/InterfaceWCF/AddUserResponse")]
    void AddUser(string numeU, string mailU, string parolaU);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/AddUser", ReplyAction="http://tempuri.org/InterfaceWCF/AddUserResponse")]
    System.Threading.Tasks.Task AddUserAsync(string numeU, string mailU, string parolaU);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/DeleteFile", ReplyAction="http://tempuri.org/InterfaceWCF/DeleteFileResponse")]
    void DeleteFile(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/DeleteFile", ReplyAction="http://tempuri.org/InterfaceWCF/DeleteFileResponse")]
    System.Threading.Tasks.Task DeleteFileAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/DeletePerson", ReplyAction="http://tempuri.org/InterfaceWCF/DeletePersonResponse")]
    void DeletePerson(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/DeletePerson", ReplyAction="http://tempuri.org/InterfaceWCF/DeletePersonResponse")]
    System.Threading.Tasks.Task DeletePersonAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/DeleteUseri", ReplyAction="http://tempuri.org/InterfaceWCF/DeleteUseriResponse")]
    void DeleteUseri(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/DeleteUseri", ReplyAction="http://tempuri.org/InterfaceWCF/DeleteUseriResponse")]
    System.Threading.Tasks.Task DeleteUseriAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/GetFiles", ReplyAction="http://tempuri.org/InterfaceWCF/GetFilesResponse")]
    ModelFirst.Files[] GetFiles(string Nume_fisier, string Cale, string Locatie, string Eveniment, string Peisaj);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/GetFiles", ReplyAction="http://tempuri.org/InterfaceWCF/GetFilesResponse")]
    System.Threading.Tasks.Task<ModelFirst.Files[]> GetFilesAsync(string Nume_fisier, string Cale, string Locatie, string Eveniment, string Peisaj);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/GetPerson", ReplyAction="http://tempuri.org/InterfaceWCF/GetPersonResponse")]
    ModelFirst.Persoane[] GetPerson(string Nume_persoana);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/GetPerson", ReplyAction="http://tempuri.org/InterfaceWCF/GetPersonResponse")]
    System.Threading.Tasks.Task<ModelFirst.Persoane[]> GetPersonAsync(string Nume_persoana);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/GetUser", ReplyAction="http://tempuri.org/InterfaceWCF/GetUserResponse")]
    ModelFirst.Useri[] GetUser(string Nume, string Mail);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/GetUser", ReplyAction="http://tempuri.org/InterfaceWCF/GetUserResponse")]
    System.Threading.Tasks.Task<ModelFirst.Useri[]> GetUserAsync(string Nume, string Mail);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/UpdateFiles", ReplyAction="http://tempuri.org/InterfaceWCF/UpdateFilesResponse")]
    void UpdateFiles(int id, string Nume_fisier, string Cale, System.DateTime Data_creare, string Locatie, string Eveniment, string Peisaj, string Descriere);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/UpdateFiles", ReplyAction="http://tempuri.org/InterfaceWCF/UpdateFilesResponse")]
    System.Threading.Tasks.Task UpdateFilesAsync(int id, string Nume_fisier, string Cale, System.DateTime Data_creare, string Locatie, string Eveniment, string Peisaj, string Descriere);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/UpdatePersoana", ReplyAction="http://tempuri.org/InterfaceWCF/UpdatePersoanaResponse")]
    void UpdatePersoana(int id, string Nume_persoana);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/UpdatePersoana", ReplyAction="http://tempuri.org/InterfaceWCF/UpdatePersoanaResponse")]
    System.Threading.Tasks.Task UpdatePersoanaAsync(int id, string Nume_persoana);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/UpdateUseri", ReplyAction="http://tempuri.org/InterfaceWCF/UpdateUseriResponse")]
    void UpdateUseri(int id, string Nume_complet, string Mail, string Parola);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/UpdateUseri", ReplyAction="http://tempuri.org/InterfaceWCF/UpdateUseriResponse")]
    System.Threading.Tasks.Task UpdateUseriAsync(int id, string Nume_complet, string Mail, string Parola);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface InterfaceWCFChannel : InterfaceWCF, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class InterfaceWCFClient : System.ServiceModel.ClientBase<InterfaceWCF>, InterfaceWCF
{
    
    public InterfaceWCFClient()
    {
    }
    
    public InterfaceWCFClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public InterfaceWCFClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public InterfaceWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public InterfaceWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void AddFile(string Nume_fisier, string Cale, System.DateTime Data_creare, string Locatie, string Eveniment, string Peisaj, string Descriere)
    {
        base.Channel.AddFile(Nume_fisier, Cale, Data_creare, Locatie, Eveniment, Peisaj, Descriere);
    }
    
    public System.Threading.Tasks.Task AddFileAsync(string Nume_fisier, string Cale, System.DateTime Data_creare, string Locatie, string Eveniment, string Peisaj, string Descriere)
    {
        return base.Channel.AddFileAsync(Nume_fisier, Cale, Data_creare, Locatie, Eveniment, Peisaj, Descriere);
    }
    
    public void AddPersoane(string Nume_persoana)
    {
        base.Channel.AddPersoane(Nume_persoana);
    }
    
    public System.Threading.Tasks.Task AddPersoaneAsync(string Nume_persoana)
    {
        return base.Channel.AddPersoaneAsync(Nume_persoana);
    }
    
    public void AddUser(string numeU, string mailU, string parolaU)
    {
        base.Channel.AddUser(numeU, mailU, parolaU);
    }
    
    public System.Threading.Tasks.Task AddUserAsync(string numeU, string mailU, string parolaU)
    {
        return base.Channel.AddUserAsync(numeU, mailU, parolaU);
    }
    
    public void DeleteFile(int id)
    {
        base.Channel.DeleteFile(id);
    }
    
    public System.Threading.Tasks.Task DeleteFileAsync(int id)
    {
        return base.Channel.DeleteFileAsync(id);
    }
    
    public void DeletePerson(int id)
    {
        base.Channel.DeletePerson(id);
    }
    
    public System.Threading.Tasks.Task DeletePersonAsync(int id)
    {
        return base.Channel.DeletePersonAsync(id);
    }
    
    public void DeleteUseri(int id)
    {
        base.Channel.DeleteUseri(id);
    }
    
    public System.Threading.Tasks.Task DeleteUseriAsync(int id)
    {
        return base.Channel.DeleteUseriAsync(id);
    }
    
    public ModelFirst.Files[] GetFiles(string Nume_fisier, string Cale, string Locatie, string Eveniment, string Peisaj)
    {
        return base.Channel.GetFiles(Nume_fisier, Cale, Locatie, Eveniment, Peisaj);
    }
    
    public System.Threading.Tasks.Task<ModelFirst.Files[]> GetFilesAsync(string Nume_fisier, string Cale, string Locatie, string Eveniment, string Peisaj)
    {
        return base.Channel.GetFilesAsync(Nume_fisier, Cale, Locatie, Eveniment, Peisaj);
    }
    
    public ModelFirst.Persoane[] GetPerson(string Nume_persoana)
    {
        return base.Channel.GetPerson(Nume_persoana);
    }
    
    public System.Threading.Tasks.Task<ModelFirst.Persoane[]> GetPersonAsync(string Nume_persoana)
    {
        return base.Channel.GetPersonAsync(Nume_persoana);
    }
    
    public ModelFirst.Useri[] GetUser(string Nume, string Mail)
    {
        return base.Channel.GetUser(Nume, Mail);
    }
    
    public System.Threading.Tasks.Task<ModelFirst.Useri[]> GetUserAsync(string Nume, string Mail)
    {
        return base.Channel.GetUserAsync(Nume, Mail);
    }
    
    public void UpdateFiles(int id, string Nume_fisier, string Cale, System.DateTime Data_creare, string Locatie, string Eveniment, string Peisaj, string Descriere)
    {
        base.Channel.UpdateFiles(id, Nume_fisier, Cale, Data_creare, Locatie, Eveniment, Peisaj, Descriere);
    }
    
    public System.Threading.Tasks.Task UpdateFilesAsync(int id, string Nume_fisier, string Cale, System.DateTime Data_creare, string Locatie, string Eveniment, string Peisaj, string Descriere)
    {
        return base.Channel.UpdateFilesAsync(id, Nume_fisier, Cale, Data_creare, Locatie, Eveniment, Peisaj, Descriere);
    }
    
    public void UpdatePersoana(int id, string Nume_persoana)
    {
        base.Channel.UpdatePersoana(id, Nume_persoana);
    }
    
    public System.Threading.Tasks.Task UpdatePersoanaAsync(int id, string Nume_persoana)
    {
        return base.Channel.UpdatePersoanaAsync(id, Nume_persoana);
    }
    
    public void UpdateUseri(int id, string Nume_complet, string Mail, string Parola)
    {
        base.Channel.UpdateUseri(id, Nume_complet, Mail, Parola);
    }
    
    public System.Threading.Tasks.Task UpdateUseriAsync(int id, string Nume_complet, string Mail, string Parola)
    {
        return base.Channel.UpdateUseriAsync(id, Nume_complet, Mail, Parola);
    }
}
