//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Files", Namespace="http://schemas.datacontract.org/2004/07/ModelFirst")]
    public partial class Files : object
    {
        
        private int IdField;
        
        private System.Collections.Generic.List<ServiceReference.Persoane> PersoanesField;
        
        private System.Collections.Generic.List<ServiceReference.Useri> UserisField;
        
        private string caleField;
        
        private System.DateTime data_creareField;
        
        private int delField;
        
        private string descriereField;
        
        private string evenimentField;
        
        private string locatieField;
        
        private string nume_fisierField;
        
        private string peisajField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReference.Persoane> Persoanes
        {
            get
            {
                return this.PersoanesField;
            }
            set
            {
                this.PersoanesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReference.Useri> Useris
        {
            get
            {
                return this.UserisField;
            }
            set
            {
                this.UserisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cale
        {
            get
            {
                return this.caleField;
            }
            set
            {
                this.caleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime data_creare
        {
            get
            {
                return this.data_creareField;
            }
            set
            {
                this.data_creareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int del
        {
            get
            {
                return this.delField;
            }
            set
            {
                this.delField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descriere
        {
            get
            {
                return this.descriereField;
            }
            set
            {
                this.descriereField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string eveniment
        {
            get
            {
                return this.evenimentField;
            }
            set
            {
                this.evenimentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string locatie
        {
            get
            {
                return this.locatieField;
            }
            set
            {
                this.locatieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nume_fisier
        {
            get
            {
                return this.nume_fisierField;
            }
            set
            {
                this.nume_fisierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string peisaj
        {
            get
            {
                return this.peisajField;
            }
            set
            {
                this.peisajField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persoane", Namespace="http://schemas.datacontract.org/2004/07/ModelFirst")]
    public partial class Persoane : object
    {
        
        private System.Collections.Generic.List<ServiceReference.Files> FilesField;
        
        private int IdField;
        
        private int delField;
        
        private string nume_persoanaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReference.Files> Files
        {
            get
            {
                return this.FilesField;
            }
            set
            {
                this.FilesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int del
        {
            get
            {
                return this.delField;
            }
            set
            {
                this.delField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nume_persoana
        {
            get
            {
                return this.nume_persoanaField;
            }
            set
            {
                this.nume_persoanaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Useri", Namespace="http://schemas.datacontract.org/2004/07/ModelFirst")]
    public partial class Useri : object
    {
        
        private System.Collections.Generic.List<ServiceReference.Files> FilesField;
        
        private int IdField;
        
        private int delField;
        
        private string mailField;
        
        private string nume_completField;
        
        private string parolaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReference.Files> Files
        {
            get
            {
                return this.FilesField;
            }
            set
            {
                this.FilesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int del
        {
            get
            {
                return this.delField;
            }
            set
            {
                this.delField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mail
        {
            get
            {
                return this.mailField;
            }
            set
            {
                this.mailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nume_complet
        {
            get
            {
                return this.nume_completField;
            }
            set
            {
                this.nume_completField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parola
        {
            get
            {
                return this.parolaField;
            }
            set
            {
                this.parolaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.InterfaceWCF")]
    public interface InterfaceWCF
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/AddFile", ReplyAction="http://tempuri.org/InterfaceWCF/AddFileResponse")]
        System.Threading.Tasks.Task AddFileAsync(string Nume_fisier, string Cale, System.DateTime Data_creare, string Locatie, string Eveniment, string Peisaj, string Descriere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/AddPersoane", ReplyAction="http://tempuri.org/InterfaceWCF/AddPersoaneResponse")]
        System.Threading.Tasks.Task AddPersoaneAsync(string Nume_persoana);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/AddUser", ReplyAction="http://tempuri.org/InterfaceWCF/AddUserResponse")]
        System.Threading.Tasks.Task AddUserAsync(string numeU, string mailU, string parolaU);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/DeleteFile", ReplyAction="http://tempuri.org/InterfaceWCF/DeleteFileResponse")]
        System.Threading.Tasks.Task DeleteFileAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/DeletePerson", ReplyAction="http://tempuri.org/InterfaceWCF/DeletePersonResponse")]
        System.Threading.Tasks.Task DeletePersonAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/DeleteUseri", ReplyAction="http://tempuri.org/InterfaceWCF/DeleteUseriResponse")]
        System.Threading.Tasks.Task DeleteUseriAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/GetFiles", ReplyAction="http://tempuri.org/InterfaceWCF/GetFilesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference.Files>> GetFilesAsync(string Nume_fisier, string Cale, string Locatie, string Eveniment, string Peisaj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/GetPerson", ReplyAction="http://tempuri.org/InterfaceWCF/GetPersonResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference.Persoane>> GetPersonAsync(string Nume_persoana);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/GetUser", ReplyAction="http://tempuri.org/InterfaceWCF/GetUserResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference.Useri>> GetUserAsync(string Nume, string Mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/UpdateFiles", ReplyAction="http://tempuri.org/InterfaceWCF/UpdateFilesResponse")]
        System.Threading.Tasks.Task UpdateFilesAsync(int id, string Nume_fisier, string Cale, System.DateTime Data_creare, string Locatie, string Eveniment, string Peisaj, string Descriere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/UpdatePersoana", ReplyAction="http://tempuri.org/InterfaceWCF/UpdatePersoanaResponse")]
        System.Threading.Tasks.Task UpdatePersoanaAsync(int id, string Nume_persoana);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceWCF/UpdateUseri", ReplyAction="http://tempuri.org/InterfaceWCF/UpdateUseriResponse")]
        System.Threading.Tasks.Task UpdateUseriAsync(int id, string Nume_complet, string Mail, string Parola);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface InterfaceWCFChannel : ServiceReference.InterfaceWCF, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class InterfaceWCFClient : System.ServiceModel.ClientBase<ServiceReference.InterfaceWCF>, ServiceReference.InterfaceWCF
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public InterfaceWCFClient() : 
                base(InterfaceWCFClient.GetDefaultBinding(), InterfaceWCFClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_InterfaceWCF.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InterfaceWCFClient(EndpointConfiguration endpointConfiguration) : 
                base(InterfaceWCFClient.GetBindingForEndpoint(endpointConfiguration), InterfaceWCFClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InterfaceWCFClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(InterfaceWCFClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InterfaceWCFClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(InterfaceWCFClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InterfaceWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task AddFileAsync(string Nume_fisier, string Cale, System.DateTime Data_creare, string Locatie, string Eveniment, string Peisaj, string Descriere)
        {
            return base.Channel.AddFileAsync(Nume_fisier, Cale, Data_creare, Locatie, Eveniment, Peisaj, Descriere);
        }
        
        public System.Threading.Tasks.Task AddPersoaneAsync(string Nume_persoana)
        {
            return base.Channel.AddPersoaneAsync(Nume_persoana);
        }
        
        public System.Threading.Tasks.Task AddUserAsync(string numeU, string mailU, string parolaU)
        {
            return base.Channel.AddUserAsync(numeU, mailU, parolaU);
        }
        
        public System.Threading.Tasks.Task DeleteFileAsync(int id)
        {
            return base.Channel.DeleteFileAsync(id);
        }
        
        public System.Threading.Tasks.Task DeletePersonAsync(int id)
        {
            return base.Channel.DeletePersonAsync(id);
        }
        
        public System.Threading.Tasks.Task DeleteUseriAsync(int id)
        {
            return base.Channel.DeleteUseriAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference.Files>> GetFilesAsync(string Nume_fisier, string Cale, string Locatie, string Eveniment, string Peisaj)
        {
            return base.Channel.GetFilesAsync(Nume_fisier, Cale, Locatie, Eveniment, Peisaj);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference.Persoane>> GetPersonAsync(string Nume_persoana)
        {
            return base.Channel.GetPersonAsync(Nume_persoana);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference.Useri>> GetUserAsync(string Nume, string Mail)
        {
            return base.Channel.GetUserAsync(Nume, Mail);
        }
        
        public System.Threading.Tasks.Task UpdateFilesAsync(int id, string Nume_fisier, string Cale, System.DateTime Data_creare, string Locatie, string Eveniment, string Peisaj, string Descriere)
        {
            return base.Channel.UpdateFilesAsync(id, Nume_fisier, Cale, Data_creare, Locatie, Eveniment, Peisaj, Descriere);
        }
        
        public System.Threading.Tasks.Task UpdatePersoanaAsync(int id, string Nume_persoana)
        {
            return base.Channel.UpdatePersoanaAsync(id, Nume_persoana);
        }
        
        public System.Threading.Tasks.Task UpdateUseriAsync(int id, string Nume_complet, string Mail, string Parola)
        {
            return base.Channel.UpdateUseriAsync(id, Nume_complet, Mail, Parola);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_InterfaceWCF))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_InterfaceWCF))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8000/PC");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return InterfaceWCFClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_InterfaceWCF);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return InterfaceWCFClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_InterfaceWCF);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_InterfaceWCF,
        }
    }
}
